typography_spectrum: 0.9872219827957451
color:
  brandStrength: 0.6745930863544345
  lightness: 0.14849838824011385
  saturation: 0.33906747843138874
  rhythmicContrast: 0.3927536644041538
  brandColors:
    - '#FFFFFF'
    - '#006697'
    - '#A7CBFD'
    - '#CC0001'
    - '#A90F0D'
layout_spectrum: 0.8061556366737932
name: Martin Graham Cloud Coaching
title: '''proximity with the team, originality of his approach, highly valuable to me.'''
description: '''A key actor in our global integration process.'''
