typography_spectrum: 0.585052611771971
color:
  brandColors:
    - '#FFFFFF'
    - '#0D6897'
    - '#000000'
    - '#CC081C'
    - '#E47F89'
  brandStrength: 0.8114209016785026
  lightness: 0.02483484405092895
  saturation: 0.8369272039271891
  rhythmicContrast: 0.5673733511939645
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.014962383545935154
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Martin Graham
  email: martin@martingraham.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6bf31504-ca90-4a55-b41c-60a3840ede04.jpg
name: Martin Graham Cloud Coaching
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Martin Graham Cloud Coaching Introduction
    id: 7cad2223-a566-4a1b-ab5f-515ed5e7cf20
    type: content
  - name: Managing my talent to keep my team and I on target
    id: b92cb68c-9f35-4aa2-addb-0778aeb0d2bc
    type: content
  - name: Four key elements essential to successful international leadership
    id: a1de0ee9-5a13-4f97-b23e-5463bcaacf46
    type: content
  - name: Contact Martin Graham
    id: c1a7ee07-f791-4477-af4b-b97858effca4
    type: content
favicon: null
title: '''A key actor in our global integration process.'' E.M. CFO Capgemini'
description: >-
  'proximity with the team, originality of his approach, highly valuable to me.'
  A.M. CIO Michelin
purpose: []
