layout_spectrum: 0.29639023705385625
typography_spectrum: 0.8744267567526549
color:
  brandStrength: 0.87712356983684
  lightness: 0.73167510679923
  saturation: 0.327038764487952
  rhythmicContrast: 0.4866976626217365
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
name: Martin Graham Cloud Coaching
navigation:
  - name: Martin Graham on Facebook
    url: 'https://www.facebook.com/martingrahamcloudcoachingltd/?ref=bookmarks'
    type: external
  - name: Martin Graham on Twitter
    url: 'https://twitter.com/martinbabel'
    type: external
  - name: Martin Graham on LinkedIn
    url: 'https://www.linkedin.com/in/martingraham'
    type: external
title: '''A key actor in our global integration process.'' E.M. CFO Capgemini'
description: >-
  'proximity with the team, originality of his approach, highly valuable to me.'
  A.M. CIO Michelin
