layout_spectrum: 0.7889661155641079
typography_spectrum: 0.1264019247610122
color:
  brandColors:
    - '#FFFFFF'
    - '#006697'
    - '#A7CBFD'
    - '#CC0001'
    - '#E67F80'
  brandStrength: 0.002612835494801402
  lightness: 0.07961020804941654
  saturation: 0.2807276137173176
  rhythmicContrast: 0.3303451912943274
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Martin Graham
  email: martin@martingraham.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6bf31504-ca90-4a55-b41c-60a3840ede04.jpg
name: Martin Graham Cloud Coaching
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Martin Graham Cloud Coaching Introduction
    id: 7cad2223-a566-4a1b-ab5f-515ed5e7cf20
    type: content
  - name: >-
      Introductory offer to experience coaching as a learning and management
      tool.
    id: b92cb68c-9f35-4aa2-addb-0778aeb0d2bc
    type: content
favicon: null
title: '''A key actor in our global integration process.'' E.M. CFO Capgemini'
description: >-
  'proximity with the team, originality of his approach, highly valuable to me.'
  A.M. CIO Michelin
purpose: []
