typography_spectrum: 0.0846304337028414
color:
  brandColors:
    - '#FFFFFF'
    - '#0D6897'
    - '#000000'
    - '#CC081C'
    - '#E47F89'
  brandStrength: 0.8100985852070153
  lightness: 0.9299546701367944
  saturation: 0.16545502096414566
  rhythmicContrast: 0.3382814626675099
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.061563356313854456
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Martin Graham
  email: martin@martingraham.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6bf31504-ca90-4a55-b41c-60a3840ede04.jpg
name: Martin Graham Cloud Coaching
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Martin Graham Cloud Coaching Introduction
    id: 7cad2223-a566-4a1b-ab5f-515ed5e7cf20
    type: content
  - name: Managing my talent to keep my team and I on target
    id: b92cb68c-9f35-4aa2-addb-0778aeb0d2bc
    type: content
  - name: Four key elements essential to successful international leadership
    id: a1de0ee9-5a13-4f97-b23e-5463bcaacf46
    type: content
favicon: null
title: '''A key actor in our global integration process.'' E.M. CFO Capgemini'
description: >-
  'proximity with the team, originality of his approach, highly valuable to me.'
  A.M. CIO Michelin
purpose: []
