name: Martin Graham Cloud Coaching
favicon: null
layout_spectrum: 0.29639023705385625
typography_spectrum: 0.8744267567526549
navigation:
  - name: Martin Graham on Facebook
    url: 'https://www.facebook.com/martingrahamcloudcoachingltd/?ref=bookmarks'
    type: external
  - name: Martin Graham on Twitter
    url: 'https://twitter.com/martinbabel'
    type: external
  - name: Martin Graham on LinkedIn
    url: 'https://www.linkedin.com/in/martingraham'
    type: external
title: '''A key actor in our global integration process.'' E.M. CFO Capgemini'
description: >-
  'proximity with the team, originality of his approach, highly valuable to me.'
  A.M. CIO Michelin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#006697'
    - '#a7cbfd'
    - '#cc0001'
    - '#be6566'
  brandStrength: 0.87712356983684
  lightness: 0.73167510679923
  saturation: 0.327038764487952
  rhythmicContrast: 0.4866976626217365
purpose: []
