typography_spectrum: 0.0845328604336828
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.12744343257509172
  lightness: 0.7918230376672
  saturation: 0.35281059332191944
  rhythmicContrast: 0.17411034437827766
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9454304955434054
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Martin Graham
  email: martin@martingraham.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6bf31504-ca90-4a55-b41c-60a3840ede04.jpg
name: Martin Graham Cloud Coaching
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Martin Graham Cloud Coaching Introduction
    id: 7cad2223-a566-4a1b-ab5f-515ed5e7cf20
    type: content
  - name: >-
      Introductory offer to experience coaching as a learning and management
      tool.
    id: b92cb68c-9f35-4aa2-addb-0778aeb0d2bc
    type: content
favicon: null
title: '''A key actor in our global integration process.'' E.M. CFO Capgemini'
description: >-
  'proximity with the team, originality of his approach, highly valuable to me.'
  A.M. CIO Michelin
purpose: []
